Configuration: Currency, Starting Coins, and Coin Value
IThundxr/CreateNumismatics pull request #92
Opened 2024-07-08 01:09 UTC by Daudeuf

New config file "numismatics-common.toml":
- Custom current currency
- Starter coins for new player accounts
- Custom coins values

2024-07-08 01:14 UTC, Daudeuf commented
@IThundxr can you post it on Curseforge when you've checked everything?

2024-07-17 12:40 UTC, banna12345bob commented
Addresses #91 & #39.

2024-07-21 15:41 UTC, IThundxr commented
Note: after some discussion we feel changing the coin values currently isn't a great idea as it could get confusing for users that play on multiple servers

2024-07-21 16:23 UTC, Daudeuf commented
It's true that changing the values between servers can be confusing. However, the current values are already confusing. I tried to introduce this into the configuration system I proposed because the players on my server were already lost.

The current values are too different from the system present in real life with divisions by multiples of 8. It would be better to have divisions by multiples of 10 and to ensure that cents are represented by only 2 objects instead of 3. This would allow for higher savings on the servers and be more representative for the players.

Finally, I understand that changing the default values at this stage of mod development is complicated, but introducing this in the configuration would be a real asset.

2024-07-21 17:16 UTC, techno-sam requested changes

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/config/CCommon.java
> +    public final ConfigEnum<Coin> defaultCoin = e(Coin.SPUR, "defaultCoin", Comments.defaultCoin);
the default should be `Coin.COG`, not `Coin.SPUR`

I'd also rename it to 'base' or 'reference' instead of 'default'

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/config/CCommon.java
> +        static final String defaultCoin = "The default coin to be used in UI related displays";
see above

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/config/CServer.java
> +        static final String starterMoney = "How much of this coin type should players receive in their bank account on first join";;
rename to `starterCurrency`

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/config/CServer.java
> +    public final ConfigInt starter_suns = i(0, 0, "starter_suns");
the Java fields should perhaps be CamelCase

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/config/NumismaticsConfig.java
> +    private static class TomlGroup {
is this needed? I believe it was added to SnR for a config migration but isn't needed here

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/backend/Coin.java
> +    public int value; // in terms of spurs
since we're not making this configurable, this should be final again. In any case, enums should not have any public mutable fields (at most a private field with an @ApiStatus.Internal setter)

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/bank/BankScreen.java
> +        Couple<Integer> cogsAndSpurs = NumismaticsConfig.common().defaultCoin.get().convert(menu.contentHolder.getBalance());
rename to `referenceAndSpurs` (or whatever is correct based on changed config field name)

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/bank/BankScreen.java
>          int cogs = cogsAndSpurs.getFirst();
rename to `reference` (or ^^^)

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/depositor/BrassDepositorBlockEntity.java
> +        Couple<Integer> cogsAndSpurs = NumismaticsConfig.common().defaultCoin.get().convert(price.getTotalPrice());
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/depositor/BrassDepositorScreen.java
> +        Couple<Integer> cogsAndSpurs = NumismaticsConfig.common().defaultCoin.get().convert(menu.contentHolder.getTotalPrice());
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/depositor/BrassDepositorScreen.java
>          int cogs = cogsAndSpurs.getFirst();
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/depositor/BrassDepositorBlockEntity.java
>          int cogs = cogsAndSpurs.getFirst();
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/vendor/VendorBlockEntity.java
> +        Couple<Integer> cogsAndSpurs = NumismaticsConfig.common().defaultCoin.get().convert(getTotalPrice());
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/vendor/VendorBlockEntity.java
>          int cogs = cogsAndSpurs.getFirst();
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/vendor/VendorScreen.java
> +        Couple<Integer> cogsAndSpurs = NumismaticsConfig.common().defaultCoin.get().convert(menu.contentHolder.getTotalPrice());
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/content/vendor/VendorScreen.java
>          int cogs = cogsAndSpurs.getFirst();
ditto

2024-07-21 17:16 UTC, techno-sam commented on common/src/main/resources/numismatics-common.toml
> +    spur = 1
this file should not exist in resources

2024-07-23 15:05 UTC, techno-sam requested changes
One nitpick and then this is good to merge

2024-07-23 15:05 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/config/CServer.java
> +    public final ConfigInt starterSuns = i(0, 0, "starterSuns");
the string names should still be underscored, I think. (e.g. `p f CI starterSuns = i(0, 0, "starter_suns");`)

2024-07-26 13:55 UTC, IThundxr approved these changes

2024-07-26 13:57 UTC, merged

2024-10-06 23:58 UTC, BredyAK commented
> It's true that changing the values between servers can be confusing. However, the current values are already confusing. I tried to introduce this into the configuration system I proposed because the players on my server were already lost.
> 
> The current values are too different from the system present in real life with divisions by multiples of 8. It would be better to have divisions by multiples of 10 and to ensure that cents are represented by only 2 objects instead of 3. This would allow for higher savings on the servers and be more representative for the players.
> 
> Finally, I understand that changing the default values at this stage of mod development is complicated, but introducing this in the configuration would be a real asset.

good point.

i feel sorry for this mod because the developer's stubbornness has severely limited its functionality. many users have submit similiar feature requests but all of them are rejected, the devs just keep their own point.

#39

2024-10-07 01:03 UTC, techno-sam commented
***Bredy, excuse me!*** I do so deeply apologize that having a unified creative vision for the mod and spending more than a year implementing features is considered "stubbornness" and "limited [...] functionality". I greatly appreciate this PR, it is genuinely good, it just had one change that didn't fit our vision. That's OK. I don't see anyone submitting ad hominem attacks to the Create devs because the gear ratio between large and small gears isn't configurable. Comments like yours are what, over time, make developers quit Minecraft modding.

Also, the mod is under a fairly permissive license. If you truly need customizable coin values for your use, feel free to make those changes yourself in your copy, rather than submitting vaguely hostile and rude comments without any contribution of work.

Before your comment, I would have been willing to discuss this with the PR *author*. Now, the very idea of doing so is offensive to me.

2024-10-07 01:40 UTC, BredyAK commented
> _**Bredy, excuse me!**_ I do so deeply apologize that having a unified creative vision for the mod and spending more than a year implementing features is considered "stubbornness" and "limited [...] functionality". I greatly appreciate this PR, it is genuinely good, it just had one change that didn't fit our vision. That's OK. I don't see anyone submitting ad hominem attacks to the Create devs because the gear ratio between large and small gears isn't configurable. Comments like yours are what, over time, make developers quit Minecraft modding.
> 
> Also, the mod is under a fairly permissive license. If you truly need customizable coin values for your use, feel free to make those changes yourself in your copy, rather than submitting vaguely hostile and rude comments without any contribution of work.
> 
> Before your comment, I would have been willing to discuss this with the PR _author_. Now, the very idea of doing so is offensive to me.

I'm sorry to offend you, and I apologize for the stubborn word.

In the discord, my questions were selectively ignored, which made me feel the attitude of the dev team was contemptuous. And, another dev like to post "¯\_(ツ)_/¯" under my posts, this makes me feel offended, and it is the direct source of my negative emotions. Again, I apologize for that.

For this feature request, I did a deeply search both on discord and github, and find so many people submitted the feature request about custom value for different currencies, but most of then are closed without any reason. (just like #39) and, in discord, the dev just told us he did a talk about this feature within the dev team and they say it does not fit the team's design style and may cause confusion for player's on different servers. TBH, why not let player's vote for this? This is just like Mojang's mob voting, it brings more hatred to the community than it's worth. This is the only thing I want to say, the dev team should listen to community's voice too.

Anyway, this is a great PR, it's such a pity to see the custom value part is rejected, and you are also the person worthy of my respect, because you bring the great work to the community, I thank you for that.

Sorry but I'm not going to use this mod because the lack of the custom value feature, and best wishes it could be added in future, i'll come back then. And wish this mod could have a brighter future.

2024-10-08 06:23 UTC, Violet-Scarelli commented
It certainly does have a bright future. Thank you for the words, but we'll take it from here.