[ComputerCraft] Add new lua functions for the Bank Terminal Peripheral
IThundxr/CreateNumismatics pull request #96
Opened 2024-07-22 09:25 UTC by banna12345bob

Adds four new lua functions to the Bank Terminal peripheral.
- `getAccounts()`
- `getAccountLabel(String accountID)`
- `getSubAccounts(String accountID)`
- `getSubAccountLabel(String accountID, String authorizationID)`

## `getAccounts()`
Gets a list of UUIDs for all accounts.
#### **Returns**
 - `list` of UUIDs for all accounts.
## `getAccountLabel(String accountID)`
Get the label of the specified account.
Throws an error if the account is not found.
#### **Returns**
- `string` the name of the specified account.
## `getSubAccounts(String accountID)`
Gives a list of UUIDs for any sub-accounts inside of specified account.
Only displays sub-accounts with authorisation type set to `Anybody`.
#### **Returns**
- `list` of UUIDs for sub-accounts
### `getSubAccountLabel(String accountID, String authorizationID)`
Returns the name for the specified sub-account inside of the specified account.
Authorisation type must be set to `Anybody` otherwise will throw an error.
#### **Returns**
- `string` the name of the specified sub-account.

2024-07-24 09:47 UTC, techno-sam commented
I don't think it's a good idea to return a list of *any* sub accounts, because someone might collect IDs and wait till they're changed to Anybody

2024-07-24 09:50 UTC, banna12345bob commented
What function are you referring to? the `getSubAccounts` function only returns accounts set to `Anybody`.

2024-08-05 19:24 UTC, techno-sam commented
That's exactly my point. I don't want people to be able to get a list of `Anybody` accounts, because those should still have the security afforded by "I was careful not to give anyone I don't trust the UUID"

2024-08-05 21:18 UTC, banna12345bob commented
How do you intend users to get uuids of accounts that the owner wants them to access? Would it be preferable to put the uuids in the accounts/sub-accounts tab? 
How would you expect users to remember all of their account uuids?

There is always a chance that malicious users read the uuid out of a already programmed computer thus rendering any security steps useless.

If you wish to contact me further about any issues with this PR I am `.constantly` on discord.

2024-08-06 12:59 UTC, techno-sam commented
Users are intended to get the UUIDs by using a computer to read them from an authorized card. Of course, malicious users could read the uuid from an *unsecured* computer, but, as long as the relevant server has some sort of claims mod, computers could be kept secure.

Other than enumerating sub accounts, I'm for merging this PR

2024-08-06 13:00 UTC, IThundxr approved these changes

2024-08-06 13:01 UTC, techno-sam requested changes
Couple of nitpicks, but very good!

2024-08-06 13:01 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/compat/computercraft/implementation/peripherals/BankTerminalPeripheral.java
> +    }
would it be helpful to also add a function that returns whether an account is player- or blaze banker-owned?

2024-08-06 13:01 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/compat/computercraft/implementation/peripherals/BankTerminalPeripheral.java
> +    public final List<String> getSubAccounts(String accountID) throws LuaException {
This function should be removed or disabled by default (subject to config), see thread above for reasons why

2024-08-06 13:40 UTC, techno-sam requested changes

2024-08-06 13:40 UTC, techno-sam commented on common/src/main/java/dev/ithundxr/createnumismatics/config/CServer.java
> +    public final ConfigBool getSubAccountsCommand = b(false, "get_sub_accounts_command");
This needs a description, then good to merge

2024-08-06 14:01 UTC, banna12345bob commented
Documentation for new function.
## `isPlayerOwned(String accountID)`
Whether a player owns the specified account or not.
#### **Returns**
 - `bool` true if account is player-owned, false if not.

2024-08-06 15:33 UTC, techno-sam approved these changes
lgtm

2024-08-06 15:34 UTC, merged